#!/usr/bin/env python3
"""Three data sources, price dropped: the final before/after.

    python3 python/multi_source.py --horizon 63

The price sleeve is excluded here on evidence, not taste. Measured on its own it
returned a Sharpe of 0.12 against the earnings sleeve's 0.52, and blending the two
equally produced 0.39, worse than earnings alone. Averaging a weak sleeve into a
strong one is dilution, and keeping it would have been sentiment about the work
already done rather than a reading of the numbers.

What remains are two sources whose data is generated by genuinely different
processes: analyst forecast error, and audited financial statements joined on
their real SEC filing dates.

Sleeves are weighted by inverse volatility rather than equally. That is the one
piece of fitting permitted here, and it is deliberately the mildest kind: it uses
only the volatility of each sleeve's returns, never their mean, so a sleeve
cannot earn weight by having been profitable in sample. It is estimated on an
expanding window so no weight is informed by the period it is applied to.
"""

from __future__ import annotations

import argparse
import sys

import numpy as np
import pandas as pd

import config
import db
import lockbox
from cross_sectional import SCORES as PRICE_SCORES, daily_ic
from earnings_book import EARNINGS_SCORES, attach_earnings, effective_n
from fundamental_signals import SIGNALS as FUND_SIGNALS, build_signals, compute
from neutral_book import book_returns, get_panel, zscore

EARN_SLEEVE = ["sue", "surprise_pct"]
FUND_SLEEVE = FUND_SIGNALS


def attach_fundamentals(panel: pd.DataFrame) -> pd.DataFrame:
    with db.connect() as con:
        facts = pd.read_sql(
            "SELECT symbol, concept, period_start, period_end, filed, val, form "
            "FROM fundamentals", con)
        # Market cap needs an unadjusted price: shares outstanding as filed times
        # the price actually quoted that day. adj_close would mix a split-adjusted
        # price with an unadjusted share count and give a nonsense market cap.
        px = pd.read_sql("SELECT symbol, dt, close FROM bars", con)
    if "close" not in panel.columns:
        panel = panel.merge(px, on=["symbol", "dt"], how="left")
    print(f"  {len(facts):,} as-filed facts, {facts['symbol'].nunique()} symbols")
    wide = build_signals(facts)
    print(f"  {len(wide):,} filing snapshots")
    out = compute(wide, panel)
    cov = out[FUND_SIGNALS].notna().mean()
    print("  coverage:", "  ".join(f"{k}={v:.0%}" for k, v in cov.items()))
    return out


def sleeve(panel: pd.DataFrame, cols: list[str], label: str) -> pd.Series:
    parts = []
    for c in cols:
        if c in panel.columns:
            parts.append(zscore(panel[c], [panel["dt"], panel["sector"]]))
    if not parts:
        return pd.Series(np.nan, index=panel.index)
    print(f"  {label}: {len(parts)} signals")
    return pd.concat(parts, axis=1).mean(axis=1, skipna=True)


def metrics(r: pd.Series, h: int) -> dict:
    if len(r) < 60:
        return {}
    s = r.to_numpy()[::h]
    if len(s) < 3 or s.std(ddof=1) == 0:
        return {}
    eq = (1 + pd.Series(s)).cumprod()
    return {"ret_ann": float(r.mean() * 252 / h),
            "vol": float(s.std(ddof=1) * np.sqrt(252 / h)),
            "sharpe": float(s.mean() / s.std(ddof=1) * np.sqrt(252 / h)),
            "t": float(s.mean() / (s.std(ddof=1) / np.sqrt(len(s)))),
            "max_dd": float(((eq.cummax() - eq) / eq.cummax()).max()),
            "n": int(len(s))}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--horizon", type=int, default=63)
    ap.add_argument("--quantiles", type=int, default=5)
    ap.add_argument("--min-adv", type=float, default=5e6)
    args = ap.parse_args()
    h, q = args.horizon, args.quantiles

    st = lockbox.state()
    max_date = (pd.Timestamp(st["seal_from"]) - pd.Timedelta(days=1)).date().isoformat()
    lockbox.guard(max_date, "multi_source")
    print(f"data through {max_date}, horizon {h}d\n")

    panel = get_panel(max_date, [h], False)
    panel = panel[panel["adv"] >= args.min_adv]
    panel = attach_earnings(panel)
    panel = attach_fundamentals(panel)
    print()

    panel["s_price"] = sleeve(panel, list(PRICE_SCORES), "price (excluded, for reference)")
    panel["s_earn"] = sleeve(panel, EARN_SLEEVE, "earnings")
    panel["s_fund"] = sleeve(panel, FUND_SLEEVE, "fundamentals")

    # Individual sleeve books, needed before weights can be formed.
    legs = {}
    for name, col in (("price", "s_price"), ("earnings", "s_earn"),
                      ("fundamentals", "s_fund")):
        r = book_returns(panel, col, h, q, True)
        if len(r) >= 60:
            legs[name] = r

    # Inverse-volatility weights on an expanding window: each period's weight
    # uses only volatility observed strictly before it.
    keep = ["earnings", "fundamentals"]
    L = pd.DataFrame({k: legs[k] for k in keep if k in legs}).dropna()
    invvol = pd.DataFrame(index=L.index, columns=L.columns, dtype=float)
    for c in L.columns:
        v = L[c].expanding(min_periods=h * 3).std().shift(1)
        invvol[c] = 1.0 / v
    w = invvol.div(invvol.sum(axis=1), axis=0)
    combo_iv = (L * w).sum(axis=1).dropna()
    combo_eq = L.mean(axis=1)

    rows = []
    for label, series in [("price only (dropped)", legs.get("price")),
                          ("earnings only", legs.get("earnings")),
                          ("fundamentals only", legs.get("fundamentals")),
                          ("earn + fund, equal wt", combo_eq),
                          ("earn + fund, inv-vol", combo_iv)]:
        if series is None or len(series) < 60:
            continue
        m = metrics(series, h)
        if m:
            rows.append({"book": label, **m})
    res = pd.DataFrame(rows)
    res.to_csv(config.ROOT / "reports" / "multi_source.csv", index=False)

    f = lambda v, s="{:.2f}": s.format(v) if (v is not None and pd.notna(v)) else "    -"
    print(f"\n{'=' * 80}\nBOOKS — sector-neutral quintiles, net of two-sided costs\n{'=' * 80}")
    print(f"{'book':<24}{'ret/yr':>10}{'vol':>8}{'Sharpe':>9}{'t':>7}{'maxDD':>9}{'n':>6}")
    for _, r in res.iterrows():
        print(f"{r.book:<24}{f(r.ret_ann,'{:+.2%}'):>10}{f(r.vol,'{:.1%}'):>8}"
              f"{f(r.sharpe):>9}{f(r.t):>7}{f(r.max_dd,'{:.1%}'):>9}{int(r.n):>6}")

    # ---------------------------------------------------- effective breadth
    print(f"\n{'=' * 80}\nEFFECTIVE BREADTH BY SOURCE COUNT\n{'=' * 80}")
    groups = {
        "price": [c for c in PRICE_SCORES],
        "earnings": EARNINGS_SCORES,
        "fundamentals": FUND_SLEEVE,
    }
    books = {}
    for g, names in groups.items():
        for n in names:
            if n not in panel.columns:
                continue
            p = panel.assign(**{n: zscore(panel[n], [panel["dt"], panel["sector"]])})
            r = book_returns(p, n, h, q, True)
            if len(r) >= 60:
                books[(g, n)] = r
    def eff(gs):
        D = pd.DataFrame({f"{g}:{n}": v for (g, n), v in books.items() if g in gs}).dropna()
        return (D.shape[1], *effective_n(D)) if D.shape[1] > 1 else (0, np.nan, np.nan)
    for label, gs in [("price only", {"price"}),
                      ("price + earnings", {"price", "earnings"}),
                      ("earnings + fundamentals", {"earnings", "fundamentals"}),
                      ("all three", {"price", "earnings", "fundamentals"})]:
        nom, neff, avg = eff(gs)
        print(f"  {label:<26}{nom:>3} nominal -> {neff:>5.1f} effective "
              f"(avg corr {avg:+.2f})")

    E = pd.DataFrame({f"{g}:{n}": v for (g, n), v in books.items()
                      if g == "earnings"}).dropna()
    F = pd.DataFrame({f"{g}:{n}": v for (g, n), v in books.items()
                      if g == "fundamentals"}).dropna()
    if not E.empty and not F.empty:
        J = E.join(F, how="inner").dropna()
        cc = J.corr().loc[E.columns, F.columns].values
        print(f"\n  cross-correlation earnings vs fundamentals: "
              f"{np.nanmean(cc):+.3f} mean, {np.nanmax(np.abs(cc)):.3f} max abs")

    best = res.sharpe.max() if not res.empty else np.nan
    print(f"\n{'=' * 80}\nVERSUS TARGET\n{'=' * 80}")
    print(f"  best book here     {best:+.3f}")
    print(f"  SPY benchmark      +0.910")
    print(f"  target             +1.500")
    print(f"  gap to target      {1.5 - best:+.3f}")
    print(f"\nwrote reports/multi_source.csv")
    return 0


if __name__ == "__main__":
    sys.exit(main())
