#!/usr/bin/env python3
"""Today's target book for the frozen short_v2 strategy.

    python3 python/v2_positions.py              # show the book
    python3 python/v2_positions.py --record     # also write it to the ledger

Produces a position list and nothing else. It places no orders, connects to no
broker, and holds no credentials. Execution is a human decision and stays one.

WHAT THIS DOES. Verifies the frozen spec's hash, rebuilds the signal exactly as
the spec describes, and prints the resulting long and short legs sized to the
gross exposure recorded in the manifest. With --record it appends the book to the
same append-only hash-chained ledger the v1 forward test uses, timestamped before
the outcome exists, which is what makes the live record evidence rather than
recollection.

If the implementing code has changed since the freeze, this refuses to run. That
is the point of the hash: a position list generated by different rules than the
ones on record is not part of the same experiment.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys

import numpy as np
import pandas as pd

import config
import db
import ledger
import lockbox
import portfolio as P
from alt_signals import attach

MODELS = config.ROOT / "models"


def verify(version: str) -> dict:
    path = MODELS / f"{version}.json"
    if not path.exists():
        raise SystemExit(f"no frozen strategy at {path}. "
                         f"Run python3 python/freeze_strategy.py")
    m = json.loads(path.read_text())
    spec = {k: m[k] for k in ("description", "signal", "universe", "construction",
                              "costs", "backtest", "live_sizing", "implemented_by")}
    h = hashlib.sha256()
    h.update(json.dumps(spec, sort_keys=True).encode())
    for p in sorted(m["implemented_by"]):
        h.update((config.ROOT / p).read_bytes())
    if h.hexdigest() != m["code_sha256"]:
        raise SystemExit(
            f"HASH MISMATCH for {version}.\n"
            f"  on record: {m['code_sha256']}\n"
            f"  computed:  {h.hexdigest()}\n"
            "The spec or the code implementing it has changed since freezing. "
            "Every result attached to this version is now unverifiable. Freeze a "
            "new version rather than continuing this record."
        )
    return m


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--version", default="short_v2")
    ap.add_argument("--record", action="store_true")
    ap.add_argument("--top", type=int, default=15, help="rows to print per leg")
    args = ap.parse_args()

    m = verify(args.version)
    print(f"{args.version} verified against its hash")
    print(f"  {m['description']}")
    gross = m["live_sizing"]["gross_exposure_usd"]
    q = m["construction"]["buckets"]
    h = m["construction"]["holding_days"]

    # Live book: no forward return exists for today, by definition.
    panel = P.build_panel("2026-12-31", h, m["universe"]["min_adv_usd"],
                          require_fwd=False)
    with db.connect() as con:
        si = pd.read_sql("SELECT symbol, tradeable_from, short_shares, prev_short, "
                         "avg_daily_vol, days_to_cover FROM short_interest", con)
    panel = attach(panel, pd.DataFrame(
        columns=["symbol", "dt", "buy_usd", "sell_usd", "n_buys"]), si)

    # The most recent date with a usable cross-section.
    d = panel.dropna(subset=["short_ratio", "beta", "size", "mom126"]).copy()
    asof = d["dt"].max()
    d = d[d["dt"] == asof].copy()
    if len(d) < 100:
        print(f"only {len(d)} names available on {asof}; not enough to form a book",
              file=sys.stderr)
        return 1

    d["s"] = (d["short_ratio"] - d.groupby("sector")["short_ratio"].transform("mean")) \
        / d.groupby("sector")["short_ratio"].transform("std").replace(0, np.nan)
    d = d.dropna(subset=["s"])
    # Residualise against the frozen factor list.
    facs = m["construction"]["residualise_against"]
    X = np.column_stack([np.ones(len(d))] + [d[f].to_numpy() for f in facs])
    ok = ~np.isnan(X).any(axis=1) & d["s"].notna().to_numpy()
    b, *_ = np.linalg.lstsq(X[ok], d.loc[ok, "s"].to_numpy(), rcond=None)
    d.loc[ok, "res"] = d.loc[ok, "s"].to_numpy() - X[ok] @ b
    d = d.dropna(subset=["res"])

    d["bucket"] = d.groupby("sector")["res"].transform(
        lambda x: pd.qcut(x.rank(method="first"), min(q, max(2, len(x) // 5)),
                          labels=False, duplicates="drop"))
    mx = d.groupby("sector")["bucket"].transform("max")
    longs = d[d["bucket"] == mx].copy()
    shorts = d[d["bucket"] == 0].copy()
    n = len(longs) + len(shorts)
    if n == 0:
        print("no positions formed", file=sys.stderr)
        return 1
    per = gross / n
    longs["usd"], shorts["usd"] = per, -per
    for leg in (longs, shorts):
        leg["shares"] = (leg["usd"].abs() / leg["close"]).round().astype(int)

    # CAPACITY CHECK. The backtested book is a full sector-wise quintile sort,
    # which on this universe is nearly six hundred names. That is unremarkable in
    # a backtest and impossible at small size: the first run of this produced $9
    # positions that rounded to zero shares for 95% of the book.
    #
    # The honest options are to size up, or to record the real book on paper and
    # keep the experiment intact. Concentrating into the strongest names would be
    # a DIFFERENT strategy from the one on record and would need its own freeze,
    # its own backtest and its own trial count. It is not done silently here.
    both = pd.concat([longs, shorts])
    zero = int((both["shares"] == 0).sum())
    median_px = float(both["close"].median())
    need_per_name = median_px * 10          # ten shares of a median-priced name
    min_gross = need_per_name * n
    if zero > n * 0.05:
        print(f"\n{'!' * 74}")
        print(f"NOT TRADEABLE AT THIS SIZE")
        print(f"{'!' * 74}")
        print(f"  the frozen book holds {n} names; at ${gross:,} gross that is "
              f"${per:,.2f} each")
        print(f"  {zero} of {n} positions ({zero/n:.0%}) round to zero shares")
        print(f"  median price in the book is ${median_px:.2f}")
        print(f"\n  a tradeable version of THIS strategy needs roughly "
              f"${min_gross:,.0f} gross")
        print(f"  (ten shares of a median-priced name in each of {n} positions),")
        print(f"  and it is a long/short book, so that is margin, not cash.")
        print(f"\n  concentrating into the strongest names would make it tradeable")
        print(f"  and would also make it a different strategy than the one frozen.")
        print(f"  that needs its own version and its own backtest, not a quiet edit.")

    print(f"\nas of {asof}   gross ${gross:,}   {len(longs)} long / {len(shorts)} short"
          f"   ${per:,.0f} per name   hold {h} sessions")
    print(f"estimated round-trip cost "
          f"${(pd.concat([longs, shorts])['half_bps'].mean() * 4 / 10_000 * gross):,.0f} "
          f"({pd.concat([longs, shorts])['half_bps'].mean() * 4:.0f}bp on gross)")

    for name, leg, sign in (("LONG", longs, 1), ("SHORT", shorts, -1)):
        leg = leg.sort_values("res", ascending=(sign < 0))
        print(f"\n{name} leg, top {min(args.top, len(leg))} by signal strength")
        print(f"  {'symbol':<8}{'sector':<26}{'price':>9}{'shares':>8}{'usd':>10}")
        for _, r in leg.head(args.top).iterrows():
            print(f"  {r.symbol:<8}{str(r.sector)[:24]:<26}{r.close:>9.2f}"
                  f"{sign * r.shares:>8}{sign * per:>10,.0f}")
        if len(leg) > args.top:
            print(f"  ... and {len(leg) - args.top} more")

    if args.record:
        v = ledger.verify()
        if not v.ok:
            print(f"\n{v}\nRefusing to append to a broken ledger.", file=sys.stderr)
            return 1
        rows = [{"kind": "v2_position", "model_version": args.version, "asof": asof,
                 "symbol": r.symbol, "side": "long" if s > 0 else "short",
                 "shares": int(r.shares), "usd": float(s * per),
                 "price_at_signal": float(r.close), "res_score": float(r.res),
                 "holding_days": h, "stage": "live"}
                for leg, s in ((longs, 1), (shorts, -1)) for r in leg.itertuples()]
        ledger.append(rows)
        print(f"\nrecorded {len(rows)} positions to the ledger, timestamped before "
              f"the outcome exists")
    else:
        print("\n(not recorded. pass --record to write this book to the ledger)")

    print("\nThis is a position list. No orders have been placed and nothing here "
          "connects to a broker.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
