#!/usr/bin/env python3
"""Total stablecoin supply (DefiLlama), a proxy for collateral behind leverage.

    python3 crypto/ingest_stablecoins.py

Levered longs on crypto venues are mostly collateralised in stablecoins, so the
outstanding supply is a slow-moving measure of the dry powder behind funding. It
is on-chain data, generated by issuance and redemption rather than by any
exchange's order book. Free, daily, back to 2017.
"""

from __future__ import annotations

import json
import sys
import urllib.request
from pathlib import Path

import pandas as pd

URL = "https://stablecoins.llama.fi/stablecoincharts/all"
OUT = Path(__file__).resolve().parent / "data" / "stablecoins.parquet"


def main() -> int:
    with urllib.request.urlopen(URL, timeout=60) as f:
        rows = json.loads(f.read().decode())
    d = pd.DataFrame({
        "date": pd.to_datetime([int(r["date"]) for r in rows], unit="s"),
        "supply": [float(r["totalCirculatingUSD"].get("peggedUSD", 0)) for r in rows],
    })
    d.to_parquet(OUT, index=False)
    print(f"stablecoins: {len(d):,} days, {d.date.min().date()} to {d.date.max().date()}, "
          f"latest ${d.supply.iloc[-1] / 1e9:,.0f}bn")
    return 0


if __name__ == "__main__":
    sys.exit(main())
